# onpod CLI — 한 줄로 끝나는 자율주행 GPU·CPU 인프라
#
# install:
#   brew tap onpod/onpod
#   brew install onpod
#
# DO NOT hand-edit version/sha256 — this file is generated by
# scripts/gen_homebrew_formula.sh from web-marketing/public/cli/{version,sha256sums}.txt.
class Onpod < Formula
  desc "onpod CLI — 한 줄로 끝나는 자율주행 GPU·CPU 인프라"
  homepage "https://onpod.ai"
  version "0.7.72"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://onpod.ai/cli/onpod-darwin-arm64?v=0.7.72"
      sha256 "48453bdcf35e047a1a46dc0cba8c6bfb3837926067ee6a9abe9f756cc01fb533"
    end
    on_intel do
      url "https://onpod.ai/cli/onpod-darwin-amd64?v=0.7.72"
      sha256 "4a08124d71884020e9f03ad47359a7216658f7304dddb8daf0d331249c8085ba"
    end
  end

  on_linux do
    on_arm do
      url "https://onpod.ai/cli/onpod-linux-arm64?v=0.7.72"
      sha256 "46afc0a11897a011cd4cfa3fa5172f21ab571f8ce21f8b017ceef64a2ee8992c"
    end
    on_intel do
      url "https://onpod.ai/cli/onpod-linux-amd64?v=0.7.72"
      sha256 "cb9e97ccb77f6cb6d5ccd26f7195dee126a2ed5d06c60a3b608f75a452ff1fa4"
    end
  end

  def install
    bin.install Dir["onpod-*"].first => "onpod"
  end

  test do
    assert_match "onpod", shell_output("#{bin}/onpod --help")
  end
end
