# onpod CLI — 한 줄로 끝나는 자율주행 GPU·CPU 인프라
#
# install:
#   brew tap onpod/onpod
#   brew install onpod
#
# DO NOT hand-edit version/sha256 — this file is generated by
# scripts/gen_homebrew_formula.sh from web-marketing/public/cli/{version,sha256sums}.txt.
class Onpod < Formula
  desc "onpod CLI — 한 줄로 끝나는 자율주행 GPU·CPU 인프라"
  homepage "https://onpod.ai"
  version "0.7.133"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://onpod.ai/cli/onpod-darwin-arm64?v=0.7.133"
      sha256 "2e23b19a677d55fd65f66f407b9e20e065701be6d336f30730b2c58940aba835"
    end
    on_intel do
      url "https://onpod.ai/cli/onpod-darwin-amd64?v=0.7.133"
      sha256 "1b63ac66d6f6085df7a4345d8f9e08b67c3cfc1147ec413f6588dba2e0d62125"
    end
  end

  on_linux do
    on_arm do
      url "https://onpod.ai/cli/onpod-linux-arm64?v=0.7.133"
      sha256 "ed74d810247681fea021cfb7dc3117a43c85666afdd65ddbba493c580d3b133a"
    end
    on_intel do
      url "https://onpod.ai/cli/onpod-linux-amd64?v=0.7.133"
      sha256 "a764e865095a8b389e9785df3463bf8566be57d1555d86cfe9c3120cfadf1b80"
    end
  end

  def install
    bin.install Dir["onpod-*"].first => "onpod"
  end

  test do
    assert_match "onpod", shell_output("#{bin}/onpod --help")
  end
end
