# onpod CLI — 한 줄로 끝나는 자율주행 GPU·CPU 인프라
#
# install:
#   brew tap onpod/onpod
#   brew install onpod
#
# DO NOT hand-edit version/sha256 — this file is generated by
# scripts/gen_homebrew_formula.sh from web-marketing/public/cli/{version,sha256sums}.txt.
class Onpod < Formula
  desc "onpod CLI — 한 줄로 끝나는 자율주행 GPU·CPU 인프라"
  homepage "https://onpod.ai"
  version "0.7.82"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://onpod.ai/cli/onpod-darwin-arm64?v=0.7.82"
      sha256 "977f5bf188d5ce2d87f665377f74c0d42ca9f26fbeabe30c3d9cfe85f5fa0c98"
    end
    on_intel do
      url "https://onpod.ai/cli/onpod-darwin-amd64?v=0.7.82"
      sha256 "3fd5283174376a2919adf553576bbee0ac09c7c2b915d07a794ecc670d333f37"
    end
  end

  on_linux do
    on_arm do
      url "https://onpod.ai/cli/onpod-linux-arm64?v=0.7.82"
      sha256 "974e504829123302f7db238f3b0091d2c3f2db19b4a344d1aba4a1d02e1e8757"
    end
    on_intel do
      url "https://onpod.ai/cli/onpod-linux-amd64?v=0.7.82"
      sha256 "54ee9c28de426caa26a3c72385ab0c27f62d9701eb0a0a7cdb01d53dfdcef409"
    end
  end

  def install
    bin.install Dir["onpod-*"].first => "onpod"
  end

  test do
    assert_match "onpod", shell_output("#{bin}/onpod --help")
  end
end
